sudo: true

language: erlang
otp_release:
  - 20.3
  - 20.2

env:
  global:
#   - ORACLE_LOGIN_userid=
    - secure: DbfrrrcALz9sTzpg/JyFA4Ds89my7hYDtqzvVUDpild85/0cG1vEClJY3JQP4FxUxI+4KhS/p4ZIJ3ubtlLJ5SX5v2QWEXmwDmjiMCbqaWgf7wFvqM+r96nZ1TTTKVYQv3oN23TLWy2py618RAOHpQVIN96oK7W19nyq00TaOZ8=
#   - ORACLE_LOGIN_pass=
    - secure: UUEW6+loLgg+83m8rsezZygw4kRCpM9xZr9rIXOIOzzu+MxpYKXGhAb80j7BeLbrmKcHlLfhPTaWNDZM6F1on9Og+Nn3DtnnMQUTO3nR15VKoHzuZYe6klnhXhjgmncukwUr1Shbh5zlC155HJuF0tonu7mWifSN7aCT1GHKx/Q=

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

  - wget https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz

  - export ORACLE_COOKIE=ic_linuxx8664
  - export ORACLE_DOWNLOAD_DIR=$(pwd)

  - export ORACLE_FILE="instantclient/121020/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm"
  - .travis/oracle/download.sh
  - export ORACLE_FILE="instantclient/121020/oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm"
  - .travis/oracle/download.sh

  - sudo apt-get install libevent-dev
  - sudo apt-get install alien dpkg-dev debhelper build-essential
  - sudo alien oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
  - sudo alien oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
  - sudo dpkg -i oracle-instantclient12.1-basic_12.1.0.2.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.1-devel_12.1.0.2.0-2_amd64.deb

  - export ORACLE_COOKIE=sqldev
  - export ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  - export ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  - export ORACLE_SID=XE

  - .travis/oracle/download.sh
  - .travis/oracle/install.sh

  - ./sqlplus sys as sysdba
  - quit

script:
  - export ERL_INTERFACE_DIR=$(ls -d /home/travis/otp/${TRAVIS_OTP_RELEASE}/lib/erl_interface-*)
  - export INSTANT_CLIENT_LIB_PATH="/usr/lib/oracle/12.1/client64/lib/"
  - export INSTANT_CLIENT_INCLUDE_PATH="/usr/include/oracle/12.1/client64/"

  - ./rebar3 compile
# - ./rebar3 ct                       % Bikram ???
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 as test coveralls send
# - ./rebar3 dialyzer                 % Bikram ???
  - ./rebar3 as test geas
