sudo: true

language: erlang
otp_release:
  - 20.3
  - 20.2

env:
  global:
    - ORACLE_COOKIE=ic_linuxx8664
    - ORACLE_DOWNLOAD_DIR=/home/travis/build/K2InformaticsGmbH/erloci
    - ORACLE_LOGIN_userid=walter.weinmann@gmail.com
    - ORACLE_LOGIN_pass=1GrossKlein

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

  - wget https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - export ORACLE_FILE=instantclient/122010/oracle-instantclient12.1-basic-12.1.0.1.0-1.x86_64.rpm
  - .travis/oracle/download.sh
  - export ORACLE_FILE=instantclient/122010/oracle-instantclient12.1-devel-12.1.0.1.0-1.x86_64.rpm
  - .travis/oracle/download.sh
  - sudo apt-get install alien
  - sudo alien oracle-instantclient12.1-basic-12.1.0.1.0-1.x86_64.rpm
  - sudo alien oracle-instantclient12.1-devel-12.1.0.1.0-1.x86_64.rpm
  - sudo dpkg -i oracle-instantclient12.1-basic_12.1.0.1.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.1-devel_12.1.0.1.0-2_amd64.deb
  - ~/.profile
  - export INSTANT_CLIENT_LIB_PATH="/usr/lib/oracle/12.1/client64/lib/"
  - export INSTANT_CLIENT_INCLUDE_PATH="/usr/include/oracle/12.1/client64/"

script:
  - ./rebar3 compile
  - ./rebar3 ct
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 as test coveralls send
