sudo: true

language: erlang
otp_release:
  - 20.3
  - 20.2

env:
  global:
    - ORACLE_COOKIE=ic_linuxx8664
    - ORACLE_DOWNLOAD_DIR=/home/travis/build/K2InformaticsGmbH/erloci
    - ORACLE_LOGIN_userid=walter.weinmann@gmail.com
    - ORACLE_LOGIN_pass=1GrossKlein

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

  - wget https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - export ORACLE_FILE=instantclient/122010/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
  - .travis/oracle/download.sh
  - export ORACLE_FILE=instantclient/122010/oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
  - .travis/oracle/download.sh
  - export ORACLE_FILE=instantclient/122010/oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
  - .travis/oracle/download.sh
  - ls -R -l
  - sudo apt-get install alien
  - sudo alien oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm
  - sudo alien oracle-instantclient12.2-devel-12.2.0.1.0-1.x86_64.rpm
  - sudo alien oracle-instantclient12.2-sqlplus-12.2.0.1.0-1.x86_64.rpm
  - ls -R -l
  - echo $(uname)
  - sudo dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb
  - sudo dpkg -i oracle-instantclient12.2-sqlplus_12.2.0.1.0-2_amd64.deb
  - ls -R -l

script:
  - ./rebar3 compile
  - ./rebar3 ct
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 as test coveralls send
