sudo: true

language: erlang
otp_release:
  - 20.3
  - 20.2

env:
  global:
    - ORACLE_CLIENT_FILE=oracle-instantclient12.2-develop-12.2.0.1.0-1.x86_64
    - ORACLE_COOKIE=ic_linuxx8664
    - ORACLE_DOWNLOAD_DIR=/home/travis/build/K2InformaticsGmbH/erloci
    - ORACLE_FILE='instantclient/122010/${ORACLE_CLIENT_FILE}.rpm'
    - ORACLE_LOGIN_userid=walter.weinmann@gmail.com
    - ORACLE_LOGIN_pass=1GrossKlein

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

  - wget https://github.com/cbandy/travis-oracle/archive/v2.0.3.tar.gz
  - mkdir -p .travis/oracle
  - tar x -C .travis/oracle --strip-components=1 -f v2.0.3.tar.gz
  - .travis/oracle/download.sh
  - pwd
  - ls
  - sudo apt-get install alien
  - sudo alien ${ORACLE_CLIENT_FILE}.rpm
  - sudo dpkg -i ${ORACLE_CLIENT_FILE}.deb

script:
  - ./rebar3 compile
  - ./rebar3 ct
  - ./rebar3 eunit
  - ./rebar3 cover
  - ./rebar3 as test coveralls send
