sudo: required
env:
  global:
    - ORACLE_COOKIE=sqldev 
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip 
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe 
    - ORACLE_SID=XE
before_install:
  - sudo apt-get install libevent-dev
  - sudo apt-get install alien dpkg-dev debhelper build-essential
  - sudo alien oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm
  - sudo alien oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
# - sudo dpkg -i oracle-instantclient12.1-basic_12.1.0.2.0-2_amd64.deb 
# - sudo dpkg -i oracle-instantclient12.1-devel_12.1.0.2.0-2_amd64.deb
  - export INSTANT_CLIENT_LIB_PATH="/usr/lib/oracle/12.1/client64/lib/"
  - export INSTANT_CLIENT_INCLUDE_PATH="/usr/include/oracle/12.1/client64/"
  - export ERL_INTERFACE_DIR="/usr/lib/erlang/lib/erl_interface-3.8.2"
  - chmod +x .travis/oracle/download.sh
  - .travis/oracle/download.sh
  - chmod +x .travis/oracle/install.sh
  - .travis/oracle/install.sh  
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
otp_release:
  - 18.3
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0
script:
  - ./rebar3 compile 
  - ./rebar3 eunit
