install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
otp_release:
  - 18.3
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0
  - 17.5
  - 17.4
  - 17.1
  - 17.0
script:
  - ./rebar3 compile 
  - ./rebar3 eunit
