sudo: required
env:
  global:
    - ORACLE_COOKIE=sqldev 
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip 
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe 
    - ORACLE_SID=XE
before_install:
  - ls -l
  - chmod +x .travis/oracle/download.sh
  - .travis/oracle/download.sh
  - ls -l
  - chmod +x .travis/oracle/install.sh
  - .travis/oracle/install.sh  
  - ls -l
  - ls -l /u01/app/oracle/11.2.0/xe
  - ls -l /home/me/download
  - sudo apt-get install libevent-dev
  - sudo apt-get install alien dpkg-dev debhelper build-essential
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
language: erlang
otp_release:
  - 18.3
  - 18.2.1
  - 18.2
  - 18.1
  - 18.0
script:
  - ./rebar3 compile 
  - ./rebar3 eunit
